# -------------------- Spawner Changer GUI Config -------------------- #
#                                                                      #
#   author  : Nightltside                                              # 
#   version : 1.6.0                                                    #
#                                                                      #
# -------------------------------------------------------------------- #
Settings:
  # Remove eggs from the GUI if the player hasn't the right permission
  RemoveNoAccessEggs: true
  # Show player's permission in the lore of items
  ShowAccessInLore: true
  # Show the cost of the change
  ShowCostInLore: true
  # Show a skull in the bottom-right corner showing the player's balance
  ShowBalanceIcon: true
  
  # How many exp should be dropped when the spawner is broken (0 for nothing)
  DroppedXPonBreak: 100.0
  # Does the player require a enchanted silktouch tool to get the spawner back
  RequireSilkTouch: true
  
  # Does the player require an item to change the spawner's type
  ItemRequirement:
    enabled: false
    item_material: EGG
    amount: 1
    
# Mob prices : the amount of money a player needs to pay in order to change 
# the spawner's type (only if Vault is hooked, a.k.a. there is an economy
# plugin on the server)
MobPrices:
  Creeper: 100.0
  Skeleton: 100.0
  Spider: 100.0
  Giant: 100.0
  Zombie: 100.0
  Slime: 100.0
  Ghast: 100.0
  Pig_Zombie: 100.0
  Enderman: 100.0
  CaveSpider: 100.0
  Silverfish: 100.0
  Blaze: 100.0
  Magma_Cube: 100.0
  Ender_Dragon: 100.0
  Wither: 100.0
  Bat: 100.0
  Witch: 100.0
  Pig: 100.0
  Sheep: 100.0
  Cow: 100.0
  Chicken: 100.0
  Squid: 100.0
  Wolf: 100.0
  Mooshroom: 100.0
  Snow_Golem: 100.0
  Ocelot: 100.0
  Iron_Golem: 100.0
  Horse: 100.0
  Villager: 100.0
  Boat: 100.0
  Minecart: 100.0
  Chest_Minecart: 100.0
  Furnace_Minecart: 100.0
  Tnt_Minecart: 100.0
  Hopper_Minecart: 100.0
  Ender_Crystal: 100.0
  Experience_Orb: 100.
  Elder_Guardian: 100.0
  Evoker: 100.0
  Llama: 100.0
  Guardian: 100.0
  Shulker: 100.0