Settings:
  SneakToOpen: false
  RemoveNoAccessEggs: true
  ShowAccessInLore: true
  ShowCostInLore: true
  ShowBalanceIcon: true
MobPrices:
  Creeper: 100.0
  Skeleton: 100.0
  Spider: 100.0
  Giant: 100.0
  Zombie: 100.0
  Slime: 100.0
  Ghast: 100.0
  PigZombie: 100.0
  Enderman: 100.0
  CaveSpider: 100.0
  Silverfish: 100.0
  Blaze: 100.0
  MagmaCube: 100.0
  EnderDragon: 100.0
  Wither: 100.0
  Bat: 100.0
  Witch: 100.0
  Pig: 100.0
  Sheep: 100.0
  Cow: 100.0
  Chicken: 100.0
  Squid: 100.0
  Wolf: 100.0
  Mooshroom: 100.0
  SnowGolem: 100.0
  Ocelot: 100.0
  IronGolem: 100.0
  Horse: 100.0
  Villager: 100.0
  Boat: 100.0
  Minecart: 100.0
  ChestMinecart: 100.0
  FurnaceMinecart: 100.0
  TntMinecart: 100.0
  HopperMinecart: 100.0
  MobSpawnerMinecart: 100.0
  EnderCrystal: 100.0
  ExperienceOrb: 100.0