author: NightlySide
main: net.nightlyside.spawnerchanger.SpawnerChangerGUI
version: '1.1.1'
name: SpawnerChangerGUI
description: "Simple & easy mobspawner modification GUI."
softdepend: [Vault]
commands:
  spawnerchangergui:
    description: Reload SpawnerChangerGUI.
    usage: /<command>
permissions:
  spawnerchangergui.open:
    default: op
  spawnerchangergui.eco.bypass.*:
    default: op
  spawnerchangergui.edit.*:
    default: false
  spawnerchangergui.recoveronbreak:
    default: op
  spawnerchangergui.reload:
    default: op
  spawnerchangergui.openonclick:
    default: true